<a href="https://colab.research.google.com/github/nehagovekar/Pandas_leetcode/blob/main/Pramp_Questions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
'''
Given the schema shown below, write a solution to find the product lines that have the highest sales volume, ranked in descending order (e.g. highest sales volume = #1, lowest sales volume = #10).


Note
Sales volume is not equal to sales revenue. Sales volume measures the quantity of products or services sold over a certain period.

users                                    products
     +---------------+---------+              +-----------------+---------+
  +--| id            | int     |        +-----| id              | int     |
  |  | first_name    | varchar |        |     | name            | varchar |
  |  | last_name     | varchar |        |  +->| product_line_id | date    |
  |  | user_city     | int     |        |  |  | stock           | int     |
  |  | email         | int     |        |  |  +-----------------+---------+
  |  +---------------+---------+        |  |
  |                                     |  |
  |     transactions                    |  |  product_lines
  |     +---------------+---------+     |  |  +--------+--------+
  |     | id            | int     |<----+  +--| id     | int    |
  +---->| customer_id   | int     |           | name   | varchar|
        | product_id    | int     |           +--------+--------+
        | amount        | int     |
        | currency_code | varchar |
        | date          | date    |
        +---------------+---------+

exchange_rate
+----------------------+---------+
| id                   | int     |
| source_currency_code | varchar |
| target_currency_code | varchar |
| rate                 | numeric |
+----------------------+---------+
Your solution should return the product line name and the total number of products sold:

rank | name    | volume
-----+---------+-------
int  | varchar | int
'''
import pandas as pd

def rank_product_lines(transactions: pd.DataFrame,
                       products: pd.DataFrame,
                       product_lines: pd.DataFrame) -> pd.DataFrame:



     df= pd.merge(transactions,products, left_on='product_id',right_on='id')
     ans=df.groupby('product_line_id')['amount'].sum()
     df_ans= pd.merge(ans, product_lines, left_on='product_line_id', right_on='id')
     df_ans['rank']=df_ans['amount'].rank(method='dense', ascending=False).astype(int)
     ans=df_ans.sort_values(by='rank').reset_index(drop=True)
     ans.rename(columns={'amount': 'volume'}, inplace=True)


     return ans[['rank','name','volume']] # your code goes here

# debug your code below
product_lines = pd.DataFrame({
    'id': [1, 2, 3],
    'name': ['Telephones', 'Kitchen', 'Clothing']
})

products = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6],
    'name': ['ePhone 10', 'Instant Cooker 2000', 'Microwave', 'Notorola X7', 'Winter Jacket', 'Bucket Hat'],
    'product_line_id': [1, 2, 2, 1, 3, 3],
    'stock': [913, 596, 911, 396, 935, 210]
})

transactions = pd.DataFrame({
    'id': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
           11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
           21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
           31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
           41, 42, 43, 44, 45, 46, 47, 48, 49, 50],
    'customer_id': [4, 9, 5, 4, 10, 3, 8, 2, 6, 2,
                    8, 10, 9, 9, 8, 1, 5, 7, 4, 2,
                    7, 7, 10, 6, 2, 6, 7, 2, 5, 9,
                    4, 8, 8, 8, 1, 2, 4, 6, 8, 9,
                    8, 2, 3, 5, 4, 2, 7, 8, 7, 3],
    'product_id': [2, 3, 2, 1, 1, 3, 5, 1, 1, 2,
                   4, 1, 1, 1, 1, 5, 5, 5, 2, 5,
                   1, 3, 4, 2, 4, 5, 5, 3, 1, 2,
                   1, 5, 2, 4, 2, 5, 5, 4, 5, 3,
                   3, 2, 4, 4, 1, 2, 4, 2, 3, 4],
    'amount': [3807, 4572, 3952, 6670, 11294, 18789, 15241, 6760, 18457, 1930,
               8049, 6019, 8294, 13446, 11472, 7129, 13056, 18599, 14766, 4757,
               12871, 8278, 4222, 9626, 8859, 9391, 7409, 15136, 17081, 19871,
               2463, 16465, 14949, 8244, 15456, 12080, 14088, 655, 16126, 10759,
               12597, 14763, 5270, 4351, 2642, 5347, 3099, 5442, 16407, 2262],
    'currency_code': ['EUR', 'USD', 'GBP', 'EUR', 'USD', 'USD', 'USD', 'EUR', 'EUR', 'USD',
                      'EUR', 'USD', 'USD', 'EUR', 'EUR', 'USD', 'USD', 'EUR', 'USD', 'USD',
                      'USD', 'USD', 'EUR', 'USD', 'USD', 'USD', 'EUR', 'USD', 'USD', 'USD',
                      'USD', 'USD', 'USD', 'USD', 'EUR', 'USD', 'USD', 'USD', 'USD', 'GBP',
                      'GBP', 'EUR', 'EUR', 'EUR', 'USD', 'EUR', 'EUR', 'EUR', 'EUR', 'EUR'],
    'date': ['2022-01-04 22:30:30', '2022-09-22 04:11:37', '2023-02-01 04:35:57', '2022-07-19 20:16:55', '2022-10-17 23:15:06',
             '2023-06-04 10:34:04', '2023-05-26 09:46:26', '2023-04-02 08:23:28', '2023-03-22 11:47:16', '2022-05-13 19:23:38',
             '2023-01-31 21:15:01', '2022-06-11 01:07:23', '2023-01-17 14:46:44', '2023-03-08 08:37:00', '2022-12-27 06:07:23',
             '2022-12-22 12:20:31', '2022-09-14 22:16:52', '2023-03-15 23:56:16', '2022-07-13 15:47:54', '2022-06-03 19:43:21',
             '2023-05-18 16:34:50', '2022-10-25 13:04:25', '2023-01-10 01:03:25', '2022-05-10 07:45:20', '2022-12-28 15:04:51',
             '2022-05-25 00:45:33', '2022-01-27 16:12:34', '2023-05-03 12:34:04', '2023-06-22 23:32:37', '2022-07-28 08:14:58',
             '2022-06-08 23:03:54', '2022-04-10 01:31:57', '2022-02-13 07:00:39', '2022-10-14 17:27:10', '2023-04-06 15:17:17',
             '2022-06-12 23:47:39', '2022-03-09 14:32:46', '2023-07-26 18:47:25', '2022-10-12 09:26:25', '2023-01-22 22:29:28',
             '2023-02-28 00:56:27', '2022-12-10 02:14:27', '2023-02-12 10:49:54', '2022-03-11 13:54:03', '2022-07-1717:23:24',
             '2023-04-13 01:22:05', '2022-10-26 23:41:33', '2022-04-05 04:37:18', '2023-05-29 08:13:32', '2022-03-20 07:38:34']})

result = rank_product_lines(transactions, products, product_lines)
print(result.to_string(index=False))